trigger:
  branches:
    include:
      - develop
    exclude:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: tpfinal-vars

stages:
  - stage: BuildFront
    displayName: Build Frontend
    jobs:
      - job: BuildNodeApp
        displayName: Build Node.js App
        steps:
          - template: templates/_build-front.yml
